version: 2

jobs:
  build_and_test:
    docker:
      - image: mccabe082/thinkcell-ci:v1
    steps:
      - checkout
      - run: cmake . -G "Ninja" -DCMAKE_C_COMPILER=/usr/local/bin/gcc -DCMAKE_CXX_COMPILER=/usr/local/bin/gcc --config Release
      - run: cmake --build . --config Release
      - run: ctest --build-config Release -VV
        