version: 2

jobs:
  build:
    docker:
      - image: mccabe082/thinkcell-ci:v1
    steps:
      - checkout
      - run: dir -a
      - run: whereis gcc
      - run: whereis cmake
      - run: cmake --help

      - run: cmake -G "Ninja" -D CMAKE_C_COMPILER=gcc-7.2
